### PR TITLE
Bump draios/sysdig to v0.35.1

### PR DESCRIPTION
**Pull request by mattnite**
It seems that my LSP caught some trailing whitespace as well, let me know if I should drop those diffs from the patch

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
cc @therealbobo we'd likely want to issue a new release, please provide context on how that works to Matt since you've been the last one refactoring the pipeline

**Review by therealbobo — APPROVED** [review]

**Comment by therealbobo** [comment]
The release process is exactly the same of `draios/sysdig`: we just need to push the new `0.10.0` and the ci will create a new release draft. Once done that, we need to convert the draft to "real" release.

@mattnite you are missing the `sysdig sign-off CLA` on the PR :)

**Comment by mattnite** [comment]
For pushing the tag, is that something you'll do once it gets merged, or is that something I should do?

**Comment by mattnite** [comment]
@therealbobo ping

**Comment by mattnite** [comment]
Nvm I realize that I needed to sign my commit

**Pull request merged**
